### ISSUE TITLE
Retorno de arquivo na rota 

### ISSUE THREAD

**Issue by rafaelgonzagag** [resultsystems/laravel-cors#3]
<p>Problema -&gt; Ao retornar um arquivo em uma rota tenho o seguinte problema:
<strong><em>'Call to undefined method Symfony\Component\HttpFoundation\BinaryFileResponse::header()'</em></strong></p>
<p>Na classe CorsMiddleware.php, no método handle() no retorno você está ligando -&gt;header() para um Response objeto que não possui essa função (Symfony\Component\HttpFoundation\BinaryFileResponseclasse).</p>
<p>A -&gt;header() função é parte de uma característica que é usada pela classe de resposta do Laravel , e não a base da Symfony Response. Felizmente, você tem acesso à headers propriedade, para que possa fazer isso. </p>
<p>Solução alterar a forma de retorno do método  handle() na classe CorsMiddleware.php para seguinte forma. </p>
<p>public function handle($request, Closure $next)
{
$allow = $this-&gt;getPermission();</p>
<pre><code>    $response = $next($request);
    $response-&gt;headers-&gt;set('Access-Control-Allow-Origin' , $allow);
    $response-&gt;headers-&gt;set('Access-Control-Allow-Methods', 'POST, GET, OPTIONS, PUT, DELETE, PATCH');
    $response-&gt;headers-&gt;set('Access-Control-Allow-Headers', 'Content-Type, Accept, Authorization, X-Requested-With, Origin');

    return $response;
}</code></pre>

**Comment by emtudo** [comment]
Olá @rafaelggads, nem testei, embora para mim funcionava o método antigo, mas como algumas pessoas reclamaram, atualizei para esta versão sua.

Espero que não dê pau em outros, rsrs, valeu pela contribuição!

**Comment by rafaelgonzagag** [comment]
Valeu!

**Comment by emtudo** [comment]
Aproveitei para fazer um pequeno refactoring
